### ISSUE TITLE
ideas to adjust display height for EK bar

### ISSUE THREAD

**Issue by RalfWerner** [knyipab/termux-x11#1]
> I wanted to thank you and contribute a few ideas. Unfortunately, the commit (#618) was deleted by termux. **Once more here:**

@knyipab You did a fantastic job! With this version, the behavior of version **1.02.04** is partially restored. However, the `opacityEKBar` option is missing here. In some cases it [would useful](https://github.com/termux/termux-x11/pull/627#issuecomment-2104162764).
![image](https://github.com/termux/termux-x11/assets/45426380/5a6fddad-5452-4274-9e3e-b6734c9a8ad8)

The implementation of the keys into [symbols](https://github.com/termux/termux-x11/assets/45426380/22093757-657a-4649-bcd8-69c31156551c) has been incomplete (**red**) since version **1.03.00**. Here a synchronized script for the EK is used in both apps. If you could correct that, it would be almost perfect for the EK. I would prefer the exclusive effect of `hideEKOnVolDown` = **true**.

I edit [Xclients](https://github.com/termux/termux-x11/assets/45426380/333595c3-d890-49ef-997f-b8e4f7686918) who use Direct mode as `touchMode`, where the use of several fingers is the typical case. With every movement of more than two fingers downwards (in X11-App), the EK is toggled on/off. If that would not be done at **true**, this problem would also be solved.

**Comment by RalfWerner** [comment]
@knyipab I ask again. You didn't respond to the first commit. You called me this place where Issues commits are preserved. **Do you still answer?**

Issue 54 in Termux was unfortunately completely deleted. There I also described the differences in the EK-X11 to EK-Termux and version 1.02.04. **Do you often use your fingers to work with Termux?**

**Comment by knyipab** [comment]
Sorry, I actually don't quite get your point. Do you mean you want those buttons HOME, END, PGUP and PGDN to be in symbol form? I don't see Termux:App by default show those symbols. Did you do extra configuration on your Termux:App?

**Comment by RalfWerner** [comment]
>Do you mean you want those buttons HOME, END, PGUP and PGDN to be in symbol form?

Exactly, configuration on my Termux:App is `extra-keys-style=arrows-all` in `~.termux/termux.properties`.  [V1.02.04 symbols](https://github.com/termux/termux-x11/assets/45426380/22093757-657a-4649-bcd8-69c31156551c) use the same Setup file.

The EK actually would only need once, like the on-screen KB. Unfortunately I could not convince the developers. So two EK are necessary for the two apps. They are displayed twice in Split/Pop view mode. Since I **switch** EK by script, both can be changed together [above](https://github.com/knyipab/termux-x11/issues/1#issue-2290842868) and **switch** itself (popup of `->`) is part of EK. Here an [Example](https://github.com/knyipab/termux-x11/assets/45426380/d274f2ca-94fa-467d-9999-2f969f086678) (28 seconds).

**Comment by RalfWerner** [comment]
> Do you often use your **fingers** to work with Termux?

You haven't said anything about this question yet. Behind the _links_ above are pictures and videos that should illustrate the text. Unfortunately, there are other problems with the **EK** bar if other devices or settings are used.

I test on 6 different devices. With @agnostic-apollo I had exchanged commits for several weeks until the current status was reached. **Are you still interested in working in a further improvement?**

**Comment by knyipab** [comment]
> Do you often use your fingers to work with Termux?
Sometimes fingers and sometimes keyboard. 

Sorry but: 
* I don't have `extra-keys-style=arrows-all` so I completely did not know what you mean since the beginning and I personally do not see that urgent need to do the feature
* Honestly I still don't quite understand many of your phrases. 

What is v1.02.04, Termux:App or Termux:X11? 
I don't think Termux:X11 can easily read `termux.properties` to know it should show arrow instead of words, right?

**Comment by RalfWerner** [comment]
> What is *v1.02.04*, Termux:App or Termux:X11?

Thanks for the reaction. First to **X11** version *v1.02.04*: That was the last one to be used as a **plugin** for Termux. You will find the **PR** [here](https://github.com/termux/termux-x11/pull/19). As with other plugins (widget, float, api ...), stronger Termux integration (shared UID) is possible. `ekeys` branch had discontinued by @suhan-paradkar in July 2022 and deleted last year by @twaik. I have a copy of it which work well with the current Termux.

In my pictures and videos above, this is used for comparison. Only _Some_ arrows are currently not implemented as in Termux . In short EK, the names are difficult to read and are cut off. Arrows would be **nice** and **like** `termux.properties` but not **urgent need.** The behavior described [above](https://github.com/knyipab/termux-x11/issues/1#issuecomment-2128685049) is more difficult. Details, when you still **interested.** If the **37** *v1.03.00* settings of **X11** are created by a script, the [synchronization](https://github.com/knyipab/termux-x11/assets/45426380/d274f2ca-94fa-467d-9999-2f969f086678) between the two `apk` is easy.

> Sometimes fingers and sometimes keyboard.

If there is a choice, I would always take the keyboard and EK would usually not be necessary. If the mouse and stylus are also available, I usually don't need fingers (except multitouch). But in my pocket I've only my phone and *not* these devices. So only fingers and touchscreen remain.
If that doesn't apply to you, you probably have no problem with **v1.03.00** and we don't need to discuss them.
My main problem with this version is the _simple gesture,_ which is currently only be solvable in _direct mode._

**Comment by RalfWerner** [comment]
> Honestly I still don't quite understand many of your phrases.

Better with the explanation above? If there is no interest, or it does not affect you, this ISSUE could be closed!

**Comment by knyipab** [comment]
Sorry, I think there is very deep context in that PR as well as your discussion and I couldn't quite pick up. So I prefer to close the issue.
