### ISSUE TITLE
Direct touch in discord

### ISSUE THREAD

**Issue by RalfWerner** [knyipab/termux-x11#2]
I can no longer post posts in Discord x11 and was apparently also blocked in other channels. So I try to go into your question here.
> 3. I don't see issue in my test. or what's the expected behavior?

**Direct** _touch_ is currently the only `touchMode` that still allowes *"simple gestures"* and supports _generic events._ However, this only works with XClients who also use it. I change my XClients to it, with the nice side effect that _pinch_ and other actions with 10 (small) fingers are possible on the touchscreen.

The last updates from @twaik (`... user actions`) are awesome! KB-Toggle can be part of EK and `Three Finger... = No Action`. This does not lead to unintentional actions - very nice!
>I am not sure, still talking with _that guy_ (Twaik).

Is _that guy_ **Peter Hutterer** (Author of `<X11/extensions/XInput2.h>`)? I also discussed with him about termux integration when you started the X11 development 5 years ago and I had a device for the first time that made it possible.
(@twaik said **No**)

If you are interested in more details about the problems and possibilities of this `touchMode`, get in touch. Otherwise you can close this issue.

**Comment by RalfWerner** [comment]
I also wrote a commit on the subject of [EK](https://discord.com/channels/641256914684084234/641256914684084237/1257289247354916864) in Discord, which was partially solved. It actually belongs to #1 but I noticed also problems with **Gboard** and one with my Samsung-KB. There are the two _MB buttons sets_ where I work on a solution for **Direct**.

@twaik meant **your own** are solved. Is that that way? you may have no interest in dealing with **mine**. If please answer and otherwise ignore.

**Comment by knyipab** [comment]
My English may be terrible. I am often confused and spend time deciphering or guessing when reading your words. And it seems that I usually invite more context and doubts when asking for clarification. Pardon me for stopping here. Thanks.

**Comment by RalfWerner** [comment]
Too bad (close) I understand your English very well. Maybe it is more mine? I often use a translator to check whether my English is easy to understand in German. Your **question** in the discord contribution is therefore sufficiently answered.
> I don't see issue in my test. or **what's the expected behavior?**
